version: '3'
services:
  httpbin:
    image: "kennethreitz/httpbin"
    ports:
     - "80"
  envoy:
    image: "envoyproxy/envoy"
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - "./envoy-reverse-proxy.yml:/etc/envoy/envoy.yaml"
